---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    # group updates in a single PR
    groups:
      ci-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "[ci]"
    labels:
      - maintenance
