---
exclude: |
  (?x)^(
      LightGBM
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        exclude: "tests"
        additional_dependencies:
          - types-requests
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--config", "pyproject.toml", "--fix"]
        types_or: [jupyter, python]
      # Run the formatter.
      - id: ruff-format
        args: ["--config", "pyproject.toml"]
        types_or: [python, jupyter]
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.12.0.1
    hooks:
      - id: shfmt
        args: ["--indent=4", "--space-redirects", "--write"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--exclude=SC2002"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
