ARG BASE_IMAGE

# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

RUN pip install --no-cache-dir \
        memray \
        pytest \
        pytest-profiling \
        snakeviz

COPY bin/profile-examples.sh /usr/local/bin/profile-examples.sh
