ARG DASK_VERSION
FROM daskdev/dask-notebook:${DASK_VERSION}

ARG DASK_VERSION
ENV \
    DASK_VERSION=${DASK_VERSION} \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update && \
    apt-get install -y \
        --no-install-recommends \
        build-essential \
        cmake \
        libomp-dev && \
    rm -rf /var/lib/apt/lists/* && \
    conda install -y \
        -c conda-forge \
        --override-channels \
            boto3 \
            dask-cloudprovider \
            scikit-learn \
            dask-ml \
            numpy \
            pandas && \
    conda clean --yes --all
