FROM python:3.11-slim

ARG DASK_VERSION=unset

ENV \
    DASK_VERSION=${DASK_VERSION} \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ARG CMAKE_VERSION="3.30.2"
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libomp-dev \
        ninja-build && \
    curl -O -L \
        https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-$(arch).sh && \
    mkdir /opt/cmake && \
    sh cmake-${CMAKE_VERSION}-linux-$(arch).sh --skip-license --prefix=/opt/cmake && \
    pip install --no-cache-dir --prefer-binary \
        'aiobotocore[awscli,boto3]>=2.5.0' \
        blosc \
        bokeh \
        dask==${DASK_VERSION} \
        'dask-cloudprovider[aws]>=2022.10.0' \
        'dask-ml>=2023.3.24' \
        distributed==${DASK_VERSION} \
        'jupyterlab>=4.0.2' \
        lz4 \
        numpy \
        'pandas>=2.0.0' \
        scikit-learn && \
    # remove unnecessary file
    find \
        /usr/local/lib/python3.11/site-packages \
        -type f \
        \( \
        -name '*.c' \
        -o -name '*.cc' \
        -o -name '*.cpp' \
        -o -name '*.h' \
        -o -name '*.hpp' \
        -o -wholename '*bokeh/sampledata/*' \
        -o -wholename '*dask/*tests/*' \
        -o -wholename '*joblib/test/*' \
        -o -wholename '*llvmlite/tests/*' \
        -o -wholename '*numba/*tests/*' \
        -o -wholename '*numpy/*tests/*' \
        -o -wholename '*pandas/*tests/*' \
        -o -wholename '*scikit-learn/tests*' \
        -o -wholename '*scikit-learn/*/tests*' \
        -o -wholename '*scipy/*/tests*' \
        -o -wholename '*tornado/test/*' \
        -o -wholename '*/__pycache__/*' \
        \) \
        -exec rm '{}' '+' && \
    find \
        /usr/local/lib/python3.11/site-packages \
        -type d \
        -wholename '*__pycache__*' \
        -exec rm -rf '{}' '+' && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--port=8888"]
