ARG BASE_IMAGE

# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

COPY . /home/jovyan/testing

RUN cd /home/jovyan/testing/LightGBM/python-package && \
    python setup.py install

WORKDIR /home/jovyan/testing/notebooks
