ARG PYTHON_VERSION=unset

FROM python:${PYTHON_VERSION}-slim

ARG CMAKE_VERSION="3.31.3"
ARG DASK_VERSION=unset
ARG PYTHON_VERSION=unset

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN --mount=type=bind,source=bin,target=/build-bin \
<<EOF
apt-get update
apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libomp-dev \
    ninja-build

bash /build-bin/install-cmake "${CMAKE_VERSION}"

python -m pip install \
    --no-cache-dir \
    --prefer-binary \
        'aiobotocore[awscli,boto3]>=2.5.0' \
        blosc \
        bokeh \
        "dask==${DASK_VERSION}" \
        'dask-cloudprovider[aws]>=2022.10.0' \
        'dask-ml>=2023.3.24' \
        "distributed==${DASK_VERSION}" \
        'jupyterlab>=4.0.2' \
        lz4 \
        numpy \
        'pandas>=2.0.0' \
        scikit-learn

# remove unnecessary files
find \
    /usr/local/lib/python${PYTHON_VERSION}/site-packages \
    -type f \
    \( \
    -name '*.c' \
    -o -name '*.cc' \
    -o -name '*.cpp' \
    -o -name '*.h' \
    -o -name '*.hpp' \
    -o -wholename '*bokeh/sampledata/*' \
    -o -wholename '*dask/*tests/*' \
    -o -wholename '*joblib/test/*' \
    -o -wholename '*llvmlite/tests/*' \
    -o -wholename '*numba/*tests/*' \
    -o -wholename '*numpy/*tests/*' \
    -o -wholename '*pandas/*tests/*' \
    -o -wholename '*scikit-learn/tests*' \
    -o -wholename '*scikit-learn/*/tests*' \
    -o -wholename '*scipy/*/tests*' \
    -o -wholename '*tornado/test/*' \
    -o -wholename '*/__pycache__/*' \
    \) \
    -exec rm '{}' '+'

find \
    /usr/local/lib/python${PYTHON_VERSION}/site-packages \
    -type d \
    -wholename '*__pycache__*' \
    -exec rm -rf '{}' '+'

# clean apt-get files
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--port=8888"]
