FROM daskdev/dask-notebook:2021.9.1

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        --no-install-recommends \
        build-essential \
        cmake && \
    rm -rf /var/lib/apt/lists/* && \
    conda install -y \
        -c conda-forge \
        --override-channels \
            boto3 \
            dask-cloudprovider \
            scikit-learn \
            dask-ml \
            numpy \
            pandas && \
    conda clean --yes --all
