ARG BASE_IMAGE
ARG INSTALL_DIR=/opt/LightGBM

# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

COPY LightGBM/ ${INSTALL_DIR}/

RUN cd "${INSTALL_DIR}" && \
    sh ./build-python.sh install --precompile && \
    cd /opt && \
    rm -rf "${INSTALL_DIR}"
