# based on https://github.com/dask/dask-docker/blob/main/notebook/Dockerfile
FROM jupyter/base-notebook:lab-3.0.5

USER root

RUN apt-get update && \
    apt-get install \
        -y \
        -q \
        --no-install-recommends \
            build-essential \
            cmake \
            curl \
            graphviz \
            git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_USER

RUN conda install --yes -c conda-forge \
        cytoolz \
        dask \
        dask-cloudprovider \
        dask-ml \
        dask-labextension>=5 \
        distributed \
        ipywidgets \
        lz4 \
        nomkl \
        numpy \
        pandas \
        python-blosc \
        python-graphviz \
        scikit-learn && \
    pip install --no-cache-dir \
        awscli && \
    conda clean --all && \
    jupyter lab clean && \
    jlpm cache clean && \
    npm cache clean --force && \
    find /opt/conda/ -type f,l -name '*.a' -delete && \
    find /opt/conda/ -type f,l -name '*.pyc' -delete && \
    find /opt/conda/ -type f,l -name '*.js.map' -delete && \
    find /opt/conda/lib/python*/site-packages/bokeh/server/static -type f,l -name '*.js' -not -name '*.min.js' -delete && \
    rm -rf /opt/conda/pkgs

USER root

RUN echo 'exec start.sh jupyter lab ${JUPYTERLAB_ARGS}' > /usr/bin/prepare.sh && \
    chmod +x /usr/bin/prepare.sh

ENTRYPOINT ["tini", "--", "/usr/bin/prepare.sh"]
