FROM daskdev/dask:latest

COPY ./LightGBM /opt/LightGBM

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake && \
    rm -rf /var/lib/apt/lists/ && \
    conda install -y -c conda-forge \
        boto3 \
        dask-cloudprovider \
        dask-ml \
        scikit-learn \
        numpy \
        pandas && \
    cd /opt/LightGBM/python-package && \
    python setup.py install && \
    cd /root && \
    rm -rf /opt/LightGBM && \
    conda clean --yes --all
