FROM python:3.11-slim

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ARG DASK_VERSION

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        libomp-dev && \
    pip install --no-cache-dir --prefer-binary \
        blosc \
        bokeh \
        dask==${DASK_VERSION} \
        'dask-ml>=2023.3.24' \
        distributed==${DASK_VERSION} \
        lz4 \
        numpy \
        'pandas>=2.0.0' \
        scikit-learn && \
    # remove unnecessary file
    find \
        /usr/local/lib/python3.11/site-packages \
        -type f \
        \( \
        -name '*.c' \
        -o -name '*.cc' \
        -o -name '*.cpp' \
        -o -name '*.h' \
        -o -name '*.hpp' \
        -o -wholename '*bokeh/sampledata/*' \
        -o -wholename '*dask/*tests/*' \
        -o -wholename '*joblib/test/*' \
        -o -wholename '*llvmlite/tests/*' \
        -o -wholename '*numba/*tests/*' \
        -o -wholename '*numpy/*tests/*' \
        -o -wholename '*pandas/*tests/*' \
        -o -wholename '*scikit-learn/tests*' \
        -o -wholename '*scikit-learn/*/tests*' \
        -o -wholename '*scipy/*/tests*' \
        -o -wholename '*tornado/test/*' \
        -o -wholename '*/__pycache__/*' \
        \) \
        -exec rm '{}' '+' && \
    find \
        /usr/local/lib/python3.11/site-packages \
        -type d \
        -wholename '*__pycache__*' \
        -exec rm -rf '{}' '+' && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
